// <auto-generated />
using System;
using CountOrSell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CountOrSell.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330000002_AddFlavorTextToCards")]
    partial class AddFlavorTextToCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountOrSell.Domain.Models.Card", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("identifier");

                    b.Property<string>("CardType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("card_type");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<decimal?>("CurrentMarketValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_market_value");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("flavor_text");

                    b.Property<bool>("IsReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reserved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("OracleRulingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oracle_ruling_url");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("set_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Identifier");

                    b.HasIndex("SetCode");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_cards_identifier", "identifier ~ '^[a-z0-9]{3,4}[0-9]{3,4}[a-z]?$' AND identifier !~ '^[a-z0-9]{3,4}0[0-9]{3}[a-z]?$'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
