// <auto-generated />
using System;
using CountOrSell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CountOrSell.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408053126_AddSetTypeAndRarity")]
    partial class AddSetTypeAndRarity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CountOrSell.Domain.Models.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.ToTable("admin_notifications", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.BackupDestinationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("configuration_json");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destination_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.ToTable("backup_destination_configs", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.BackupDestinationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("BackupRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_record_id");

                    b.Property<string>("DestinationLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination_label");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destination_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("BackupRecordId");

                    b.ToTable("backup_destination_records", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("backup_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.ToTable("backup_records", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.Card", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("identifier");

                    b.Property<string>("CardType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("card_type");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<decimal?>("CurrentMarketValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_market_value");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("flavor_text");

                    b.Property<bool>("IsReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reserved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("OracleRulingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oracle_ruling_url");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rarity");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("set_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Identifier");

                    b.HasIndex("SetCode");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_cards_identifier", "identifier ~ '^[a-z0-9]{3,4}([0-9]{3}|[1-9][0-9]{3})[a-z]?$'");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.CollectionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<decimal>("AcquisitionPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acquisition_price");

                    b.Property<bool>("Autographed")
                        .HasColumnType("boolean")
                        .HasColumnName("autographed");

                    b.Property<string>("CardIdentifier")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("card_identifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("TreatmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("treatment_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CardIdentifier");

                    b.HasIndex("TreatmentKey");

                    b.HasIndex("UserId");

                    b.ToTable("collection_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_collection_entries_card_identifier", "card_identifier ~ '^[a-z0-9]{3,4}([0-9]{3}|[1-9][0-9]{3})[a-z]?$'");

                            t.HasCheckConstraint("CK_collection_entries_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.GradingAgency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<bool>("SupportsDirectLookup")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_direct_lookup");

                    b.Property<string>("ValidationUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("validation_url_template");

                    b.HasKey("Code");

                    b.ToTable("grading_agencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "bgs",
                            Active = true,
                            FullName = "Beckett Grading Services",
                            Source = "Canonical",
                            SupportsDirectLookup = true,
                            ValidationUrlTemplate = "https://www.beckett.com/grading"
                        },
                        new
                        {
                            Code = "psa",
                            Active = true,
                            FullName = "Professional Sports Authenticator",
                            Source = "Canonical",
                            SupportsDirectLookup = true,
                            ValidationUrlTemplate = "https://www.psacard.com/cert/{0}"
                        },
                        new
                        {
                            Code = "sgc",
                            Active = true,
                            FullName = "Sportscard Guaranty",
                            Source = "Canonical",
                            SupportsDirectLookup = true,
                            ValidationUrlTemplate = "https://www.sgccard.com/cert/{0}"
                        },
                        new
                        {
                            Code = "cgc",
                            Active = true,
                            FullName = "Certified Guaranty Company",
                            Source = "Canonical",
                            SupportsDirectLookup = true,
                            ValidationUrlTemplate = "https://www.cgccards.com/certlookup/{0}"
                        },
                        new
                        {
                            Code = "ccc",
                            Active = true,
                            FullName = "Certificateur de Cartes de Collection",
                            Source = "Canonical",
                            SupportsDirectLookup = false,
                            ValidationUrlTemplate = "https://cccgrading.com/en/ccc-card-verification"
                        },
                        new
                        {
                            Code = "isa",
                            Active = true,
                            FullName = "International Sports Authentication",
                            Source = "Canonical",
                            SupportsDirectLookup = true,
                            ValidationUrlTemplate = "https://www.isagrading.com/verify/{0}"
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.PendingSchemaUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("download_url");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_version");

                    b.Property<string>("ZipSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zip_sha256");

                    b.HasKey("Id");

                    b.ToTable("pending_schema_updates", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedInventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<decimal>("AcquisitionPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acquisition_price");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_slug");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_identifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SubTypeSlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_type_slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategorySlug");

                    b.HasIndex("SubTypeSlug");

                    b.HasIndex("UserId");

                    b.ToTable("sealed_inventory_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_sealed_inventory_entries_quantity", "quantity > 0");

                            t.HasCheckConstraint("CK_sealed_inventory_entries_sub_type_slug", "sub_type_slug IS NULL OR category_slug IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedProduct", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.Property<string>("CategorySlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_slug");

                    b.Property<decimal?>("CurrentMarketValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_market_value");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("set_code");

                    b.Property<string>("SubTypeSlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_type_slug");

                    b.Property<string>("Upc")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("upc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Identifier");

                    b.HasIndex("CategorySlug");

                    b.HasIndex("SetCode");

                    b.HasIndex("SubTypeSlug");

                    b.ToTable("sealed_products", null, t =>
                        {
                            t.HasCheckConstraint("CK_sealed_products_upc", "upc IS NULL OR upc ~ '^\\d{12,13}$'");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedProductCategory", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Slug");

                    b.ToTable("sealed_product_categories", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedProductSubType", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_slug");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Slug");

                    b.HasIndex("CategorySlug");

                    b.ToTable("sealed_product_sub_types", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SerializedEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<decimal>("AcquisitionPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acquisition_price");

                    b.Property<bool>("Autographed")
                        .HasColumnType("boolean")
                        .HasColumnName("autographed");

                    b.Property<string>("CardIdentifier")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("card_identifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PrintRunTotal")
                        .HasColumnType("integer")
                        .HasColumnName("print_run_total");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("serial_number");

                    b.Property<string>("TreatmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("treatment_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentKey");

                    b.HasIndex("UserId");

                    b.ToTable("serialized_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_serialized_entries_card_identifier", "card_identifier ~ '^[a-z0-9]{3,4}([0-9]{3}|[1-9][0-9]{3})[a-z]?$'");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.Set", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<bool>("Digital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("digital");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("SetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("set_type");

                    b.Property<int>("TotalCards")
                        .HasColumnType("integer")
                        .HasColumnName("total_cards");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Code");

                    b.ToTable("sets", null, t =>
                        {
                            t.HasCheckConstraint("CK_sets_code", "code ~ '^[a-z0-9]{3,4}$'");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SlabEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<decimal>("AcquisitionPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acquisition_price");

                    b.Property<bool>("Autographed")
                        .HasColumnType("boolean")
                        .HasColumnName("autographed");

                    b.Property<string>("CardIdentifier")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("card_identifier");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certificate_number");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grade");

                    b.Property<string>("GradingAgencyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grading_agency_code");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int?>("PrintRunTotal")
                        .HasColumnType("integer")
                        .HasColumnName("print_run_total");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("serial_number");

                    b.Property<string>("TreatmentKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("treatment_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GradingAgencyCode");

                    b.HasIndex("TreatmentKey");

                    b.HasIndex("UserId");

                    b.ToTable("slab_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_slab_entries_card_identifier", "card_identifier ~ '^[a-z0-9]{3,4}([0-9]{3}|[1-9][0-9]{3})[a-z]?$'");

                            t.HasCheckConstraint("CK_slab_entries_print_run_total", "serial_number IS NULL OR print_run_total IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.Treatment", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Key");

                    b.ToTable("treatments", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.UpdateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_version");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_version");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.ToTable("update_versions", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBuiltinAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin_admin");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oauth_provider");

                    b.Property<string>("OAuthProviderUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oauth_provider_user_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("OAuthProvider", "OAuthProviderUserId")
                        .IsUnique()
                        .HasFilter("oauth_provider IS NOT NULL AND oauth_provider_user_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.UserExportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTime>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_export_files", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("user_invitations", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("DefaultAcquisitionPriceToMarket")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultPage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_page");

                    b.Property<bool>("SetCompletionRegularOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("set_completion_regular_only");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.WishlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardIdentifier")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("card_identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CardIdentifier")
                        .IsUnique();

                    b.ToTable("wishlist_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_wishlist_entries_card_identifier", "card_identifier ~ '^[a-z0-9]{3,4}([0-9]{3}|[1-9][0-9]{3})[a-z]?$'");
                        });
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.BackupDestinationRecord", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.BackupRecord", null)
                        .WithMany("Destinations")
                        .HasForeignKey("BackupRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.Card", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.CollectionEntry", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedInventoryEntry", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.SealedProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategorySlug")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CountOrSell.Domain.Models.SealedProductSubType", null)
                        .WithMany()
                        .HasForeignKey("SubTypeSlug")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedProduct", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.SealedProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategorySlug")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CountOrSell.Domain.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountOrSell.Domain.Models.SealedProductSubType", null)
                        .WithMany()
                        .HasForeignKey("SubTypeSlug")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SealedProductSubType", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.SealedProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategorySlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SerializedEntry", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.SlabEntry", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.GradingAgency", "GradingAgency")
                        .WithMany()
                        .HasForeignKey("GradingAgencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountOrSell.Domain.Models.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingAgency");

                    b.Navigation("Treatment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.UserPreferences", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CountOrSell.Domain.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.WishlistEntry", b =>
                {
                    b.HasOne("CountOrSell.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.BackupRecord", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("CountOrSell.Domain.Models.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
