using CountOrSell.Wizard.Models;

namespace CountOrSell.Wizard.Services;

public static class DockerComposeGenerator
{
    public static string Generate(WizardConfig config)
    {
        var imageRepo = config.DockerRegistry ?? "ghcr.io/darkgrotto/countorsell";
        var tag = string.IsNullOrEmpty(config.DockerImageTag) ? "latest" : config.DockerImageTag;
        var appImage = $"{imageRepo}:{tag}";

        return $@"# Generated by CountOrSell first-run wizard. Do not edit manually.
# To regenerate, run the wizard again.
version: '3.8'

services:
  app:
    image: {appImage}
    environment:
      - POSTGRES_CONNECTION=Host=postgres;Database=countorsell;Username={config.DbAdminUsername};Password={config.DbAdminPassword}
      - INSTANCE_NAME={config.InstanceName}
      - UPDATE_CHECK_TIME={config.UpdateCheckTime}
      - BACKUP_SCHEDULE={config.BackupSchedule}
      - BACKUP_RETENTION={config.BackupRetention}
      - BLOB_BACKUP_CONNECTION={config.BackupConnectionString}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=countorsell
      - POSTGRES_USER={config.DbAdminUsername}
      - POSTGRES_PASSWORD={config.DbAdminPassword}
    volumes:
      - countorsell_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [""CMD-SHELL"", ""pg_isready -U {config.DbAdminUsername} -d countorsell""]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  reverse-proxy:
    image: nginx:alpine
    ports:
      - ""{config.Port}:443""
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certs:/etc/nginx/certs:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  countorsell_postgres_data:
    name: countorsell_postgres_data
";
    }
}
