using CountOrSell.Wizard.Models;

namespace CountOrSell.Wizard.Services;

public static class TerraformApplyGenerator
{
    public static string Generate(WizardConfig config)
    {
        return config.DeploymentType switch
        {
            DeploymentType.Azure => GenerateAzure(config),
            DeploymentType.Aws   => GenerateAws(config),
            DeploymentType.Gcp   => GenerateGcp(config),
            _                    => throw new InvalidOperationException("No Terraform apply script for Docker deployments.")
        };
    }

    private static string GenerateAzure(WizardConfig config)
    {
        var stateRg      = config.CloudStateResourceGroup  ?? string.Empty;
        var stateAccount = config.CloudStateStorageAccount ?? string.Empty;

        return
@"#!/bin/bash
# Generated by CountOrSell first-run wizard. Do not edit manually.
# Usage: ./terraform-apply.sh
# Applies Terraform configuration for your Azure CountOrSell deployment.
# Requires an active Azure CLI login: az login

set -euo pipefail

SCRIPT_DIR=""$(cd ""$(dirname ""${BASH_SOURCE[0]}"")"" && pwd)""
TF_DIR=""$SCRIPT_DIR/infrastructure/azure""

echo ""Checking Azure login...""
if ! az account show --output none 2>/dev/null; then
    echo ""Not logged in to Azure. Run: az login""
    exit 1
fi

cd ""$TF_DIR""

echo ""Running: terraform init""
terraform init -input=false \
    -backend-config=""resource_group_name=STATE_RG"" \
    -backend-config=""storage_account_name=STATE_ACCOUNT""

echo ""Running: terraform plan""
terraform plan -input=false -var-file=terraform.tfvars

read -r -p ""Apply these changes? [y/N]: "" confirm
if [[ ""${confirm,,}"" == ""y"" ]]; then
    terraform apply -auto-approve -input=false -var-file=terraform.tfvars
    echo ""Terraform apply complete.""
else
    echo ""Apply cancelled.""
fi
"
        .Replace("STATE_RG",      stateRg)
        .Replace("STATE_ACCOUNT", stateAccount);
    }

    private static string GenerateAws(WizardConfig config)
    {
        var bucket = config.CloudStateBucket ?? string.Empty;
        var region = config.CloudRegion      ?? "us-east-1";

        return
@"#!/bin/bash
# Generated by CountOrSell first-run wizard. Do not edit manually.
# Usage: ./terraform-apply.sh
# Applies Terraform configuration for your AWS CountOrSell deployment.
# Requires valid AWS credentials: aws configure or AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY env vars.

set -euo pipefail

SCRIPT_DIR=""$(cd ""$(dirname ""${BASH_SOURCE[0]}"")"" && pwd)""
TF_DIR=""$SCRIPT_DIR/infrastructure/aws""

echo ""Checking AWS credentials...""
if ! aws sts get-caller-identity --output none 2>/dev/null; then
    echo ""AWS credentials not configured. Run: aws configure""
    exit 1
fi

cd ""$TF_DIR""

echo ""Running: terraform init""
terraform init -input=false \
    -backend-config=""bucket=STATE_BUCKET"" \
    -backend-config=""region=STATE_REGION""

echo ""Running: terraform plan""
terraform plan -input=false -var-file=terraform.tfvars

read -r -p ""Apply these changes? [y/N]: "" confirm
if [[ ""${confirm,,}"" == ""y"" ]]; then
    terraform apply -auto-approve -input=false -var-file=terraform.tfvars
    echo ""Terraform apply complete.""
else
    echo ""Apply cancelled.""
fi
"
        .Replace("STATE_BUCKET", bucket)
        .Replace("STATE_REGION", region);
    }

    private static string GenerateGcp(WizardConfig config)
    {
        var bucket = config.CloudStateBucket ?? string.Empty;

        return
@"#!/bin/bash
# Generated by CountOrSell first-run wizard. Do not edit manually.
# Usage: ./terraform-apply.sh
# Applies Terraform configuration for your GCP CountOrSell deployment.
# Requires active gcloud credentials:
#   gcloud auth login
#   gcloud auth application-default login

set -euo pipefail

SCRIPT_DIR=""$(cd ""$(dirname ""${BASH_SOURCE[0]}"")"" && pwd)""
TF_DIR=""$SCRIPT_DIR/infrastructure/gcp""

echo ""Checking gcloud credentials...""
if ! gcloud auth print-access-token --quiet 2>/dev/null; then
    echo ""Not logged in to gcloud. Run: gcloud auth login""
    exit 1
fi

cd ""$TF_DIR""

echo ""Running: terraform init""
terraform init -input=false \
    -backend-config=""bucket=STATE_BUCKET""

echo ""Running: terraform plan""
terraform plan -input=false -var-file=terraform.tfvars

read -r -p ""Apply these changes? [y/N]: "" confirm
if [[ ""${confirm,,}"" == ""y"" ]]; then
    terraform apply -auto-approve -input=false -var-file=terraform.tfvars
    echo ""Terraform apply complete.""
else
    echo ""Apply cancelled.""
fi
"
        .Replace("STATE_BUCKET", bucket);
    }
}
