#!/bin/bash
# Generated by CountOrSell first-run wizard. Do not edit manually.
# To regenerate, run the wizard again.
#
# Usage: ./update.sh
# This script updates the CountOrSell application to the latest version.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/../compose/docker-compose.yml"

echo "Pulling latest CountOrSell images..."
# Pull the latest versions of all images defined in the Compose file
docker compose -f "$COMPOSE_FILE" pull

echo "Restarting services with updated images..."
# Recreate containers with the new images (zero-downtime where possible)
docker compose -f "$COMPOSE_FILE" up -d

echo "Update complete."
