using CountOrSell.Wizard.Models;
using CountOrSell.Wizard.Services;

namespace CountOrSell.Wizard.Steps;

public static class Step15_GenerateFiles
{
    public static Task RunAsync(WizardConfig config)
    {
        Console.WriteLine("Step 15 of 17: Generate Configuration Files");
        Console.WriteLine("--------------------------------------------");

        if (config.DeploymentType == DeploymentType.Docker)
        {
            GenerateDockerFiles(config);
        }
        else
        {
            GenerateCloudFiles(config);
        }

        WriteWizardEnvFile(config);

        Console.WriteLine();
        return Task.CompletedTask;
    }

    private static void GenerateCloudFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var scriptPath = Path.Combine(baseDir, "terraform-apply.sh");

        var content = TerraformApplyGenerator.Generate(config);
        File.WriteAllText(scriptPath, content);

        if (!OperatingSystem.IsWindows())
        {
            System.Diagnostics.Process.Start("chmod", $"+x \"{scriptPath}\"");
        }

        Console.WriteLine($"Generated: {scriptPath}");
        Console.WriteLine("Terraform files are in the infrastructure/ directory.");
        Console.WriteLine("Terraform apply will be run in Step 16.");
    }

    private static void GenerateDockerFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();

        var composeDir = Path.Combine(baseDir, "docker", "compose");
        var scriptsDir = Path.Combine(baseDir, "docker", "scripts");

        Directory.CreateDirectory(composeDir);
        Directory.CreateDirectory(scriptsDir);

        var composeContent = DockerComposeGenerator.Generate(config);
        var composePath = Path.Combine(composeDir, "docker-compose.yml");
        File.WriteAllText(composePath, composeContent);
        Console.WriteLine($"Generated: {composePath}");

        var updateShContent = UpdateShGenerator.Generate();
        var updateShPath = Path.Combine(scriptsDir, "update.sh");
        File.WriteAllText(updateShPath, updateShContent);

        // Make executable on non-Windows
        if (!OperatingSystem.IsWindows())
        {
            System.Diagnostics.Process.Start("chmod", $"+x \"{updateShPath}\"");
        }

        Console.WriteLine($"Generated: {updateShPath}");
    }

    private static void WriteWizardEnvFile(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var envPath = Path.Combine(baseDir, ".env");

        var lines = new List<string>
        {
            "# Generated by CountOrSell first-run wizard. Do not edit manually.",
            $"INSTANCE_NAME={config.InstanceName}",
            $"UPDATE_CHECK_TIME={config.UpdateCheckTime}",
            $"BACKUP_SCHEDULE={config.BackupSchedule}",
            $"BACKUP_RETENTION={config.BackupRetention}",
            $"DB_USER={config.DbAdminUsername}",
            $"DB_PASSWORD={config.DbAdminPassword}",
            $"REGISTRY={config.DockerRegistry ?? string.Empty}",
            $"PORT={config.Port}",
            $"BLOB_BACKUP_CONNECTION={config.BackupConnectionString}"
        };

        File.WriteAllLines(envPath, lines);
        Console.WriteLine($"Generated: {envPath}");
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "CLAUDE.md")))
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return AppContext.BaseDirectory;
    }
}
