using CountOrSell.Wizard.Models;
using CountOrSell.Wizard.Services;

namespace CountOrSell.Wizard.Steps;

public static class Step15_GenerateFiles
{
    public static Task RunAsync(WizardConfig config)
    {
        Console.WriteLine("Step 15 of 17: Generate Configuration Files");
        Console.WriteLine("--------------------------------------------");

        // Generate a one-time setup token before any files are written.
        // It is embedded in the deployment environment and sent by the wizard during
        // Step 16 to authenticate the account-creation call.
        config.SetupToken = Convert.ToHexString(
            System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));

        if (config.DeploymentType == DeploymentType.Docker)
        {
            GenerateDockerFiles(config);
        }
        else
        {
            GenerateCloudFiles(config);
        }

        WriteWizardEnvFile(config);

        Console.WriteLine();
        return Task.CompletedTask;
    }

    private static void GenerateCloudFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var scriptPath = Path.Combine(baseDir, "terraform-apply.sh");

        var content = TerraformApplyGenerator.Generate(config);
        File.WriteAllText(scriptPath, content);

        if (!OperatingSystem.IsWindows())
        {
            System.Diagnostics.Process.Start("chmod", $"+x \"{scriptPath}\"");
        }

        Console.WriteLine($"Generated: {scriptPath}");
        Console.WriteLine("Terraform files are in the infrastructure/ directory.");
        Console.WriteLine("Terraform apply will be run in Step 16.");
    }

    private static void GenerateDockerFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();

        var composeDir = Path.Combine(baseDir, "docker", "compose");
        var scriptsDir = Path.Combine(baseDir, "docker", "scripts");

        Directory.CreateDirectory(composeDir);
        Directory.CreateDirectory(scriptsDir);

        var composeContent = DockerComposeGenerator.Generate(config);
        var composePath = Path.Combine(composeDir, "docker-compose.yml");
        File.WriteAllText(composePath, composeContent);
        Console.WriteLine($"Generated: {composePath}");

        var updateShContent = UpdateShGenerator.Generate();
        var updateShPath = Path.Combine(scriptsDir, "update.sh");
        File.WriteAllText(updateShPath, updateShContent);

        // Make executable on non-Windows
        if (!OperatingSystem.IsWindows())
        {
            System.Diagnostics.Process.Start("chmod", $"+x \"{updateShPath}\"");
        }

        Console.WriteLine($"Generated: {updateShPath}");
    }

    // The .env file is where every secret lives. The Compose file is tracked in git and
    // carries only variable references, so this is the one generated artifact that must
    // never be committed - .gitignore already covers it.
    private static void WriteWizardEnvFile(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var envPath = Path.Combine(baseDir, ".env");

        var lines = new List<string>
        {
            "# Generated by CountOrSell first-run wizard. Do not edit manually.",
            "# Contains credentials - never commit this file.",
            EnvLine("INSTANCE_NAME", config.InstanceName),
            EnvLine("UPDATE_CHECK_TIME", config.UpdateCheckTime),
            EnvLine("BACKUP_SCHEDULE", config.BackupSchedule),
            EnvLine("BACKUP_RETENTION", config.BackupRetention.ToString()),
            EnvLine("DB_NAME", "countorsell"),
            EnvLine("DB_USER", config.DbAdminUsername),
            EnvLine("DB_PASSWORD", config.DbAdminPassword),
            // Defaulted rather than left blank: an empty REGISTRY expands to a leading
            // slash and Docker rejects the reference outright.
            EnvLine("REGISTRY", string.IsNullOrWhiteSpace(config.DockerRegistry)
                ? "ghcr.io/darkgrotto"
                : config.DockerRegistry),
            EnvLine("PORT", config.Port.ToString()),
            EnvLine("BLOB_BACKUP_CONNECTION", config.BackupConnectionString),
            EnvLine("SETUP_TOKEN", config.SetupToken)
        };

        File.WriteAllLines(envPath, lines);
        RestrictToOwner(envPath);
        Console.WriteLine($"Generated: {envPath}");
    }

    // Compose interpolates variables inside .env values, so a literal $ - entirely legal in
    // a password - would otherwise be read as the start of a reference and silently mangle
    // the value. $$ is Compose's escape for it.
    private static string EnvLine(string key, string? value)
        => $"{key}={(value ?? string.Empty).Replace("$", "$$")}";

    // The file holds the database password and setup token, so keep it owner-only.
    // No-op on Windows, where the default ACL on a user-profile path is already restrictive.
    private static void RestrictToOwner(string path)
    {
        if (OperatingSystem.IsWindows()) return;
        try
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Warning: could not restrict permissions on {path}: {ex.Message}");
        }
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "CLAUDE.md")))
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return AppContext.BaseDirectory;
    }
}
