using CountOrSell.Wizard.Models;
using CountOrSell.Wizard.Services;

namespace CountOrSell.Wizard.Steps;

public static class Step14_GenerateFiles
{
    public static Task RunAsync(WizardConfig config)
    {
        Console.WriteLine("Step 14 of 16: Generate Configuration Files");
        Console.WriteLine("--------------------------------------------");

        // Generate a one-time setup token before any files are written.
        // It is embedded in the deployment environment and sent by the wizard during
        // Step 16 to authenticate the account-creation call.
        config.SetupToken = Convert.ToHexString(
            System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));

        if (config.DeploymentType == DeploymentType.Docker)
        {
            GenerateDockerFiles(config);
        }
        else
        {
            GenerateCloudFiles(config);
        }

        WriteWizardEnvFile(config);

        Console.WriteLine();
        return Task.CompletedTask;
    }

    private static void GenerateCloudFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var scriptPath = Path.Combine(baseDir, "terraform-apply.sh");

        var content = TerraformApplyGenerator.Generate(config);
        File.WriteAllText(scriptPath, content);

        MakeExecutable(scriptPath);

        Console.WriteLine($"Generated: {scriptPath}");
        Console.WriteLine("Terraform files are in the infrastructure/ directory.");
        Console.WriteLine("Terraform apply will be run in Step 16.");
    }

    private static void GenerateDockerFiles(WizardConfig config)
    {
        var baseDir = FindRepoRoot();

        var composeDir = Path.Combine(baseDir, "docker", "compose");
        var scriptsDir = Path.Combine(baseDir, "docker", "scripts");

        Directory.CreateDirectory(composeDir);
        Directory.CreateDirectory(scriptsDir);

        var composeContent = DockerComposeGenerator.Generate(config);
        var composePath = Path.Combine(composeDir, "docker-compose.yml");
        File.WriteAllText(composePath, composeContent);
        Console.WriteLine($"Generated: {composePath}");

        var updateShContent = UpdateShGenerator.Generate();
        var updateShPath = Path.Combine(scriptsDir, "update.sh");
        File.WriteAllText(updateShPath, updateShContent);

        MakeExecutable(updateShPath);

        Console.WriteLine($"Generated: {updateShPath}");
    }

    // The .env file is where every secret lives. The Compose file is tracked in git and
    // carries only variable references, so this is the one generated artifact that must
    // never be committed - .gitignore already covers it.
    private static void WriteWizardEnvFile(WizardConfig config)
    {
        var baseDir = FindRepoRoot();
        var envPath = Path.Combine(baseDir, ".env");

        var lines = new List<string>
        {
            "# Generated by CountOrSell first-run wizard. Do not edit manually.",
            "# Contains credentials - never commit this file.",
            // Scopes the Compose project, container names and volumes, so several
            // CountOrSell deployments can coexist on one Docker host.
            EnvLine("COS_PROJECT_NAME", ProjectNameFrom(config.InstanceName)),
            EnvLine("INSTANCE_NAME", config.InstanceName),
            EnvLine("UPDATE_CHECK_TIME", config.UpdateCheckTime),
            EnvLine("BACKUP_SCHEDULE", config.BackupSchedule),
            EnvLine("BACKUP_RETENTION", config.BackupRetention.ToString()),
            EnvLine("DB_NAME", "countorsell"),
            EnvLine("DB_USER", config.DbAdminUsername),
            EnvLine("DB_PASSWORD", config.DbAdminPassword),
            // The full image reference, not a registry prefix: the Step 3 prompt collects
            // the whole repository path, so composing it with a separate image name would
            // yield ".../countorsell/countorsell". Defaulted rather than left blank,
            // because an empty value produces a reference Docker rejects outright.
            EnvLine("APP_IMAGE", BuildAppImage(config)),
            EnvLine("PORT", config.Port.ToString()),
            EnvLine("BLOB_BACKUP_CONNECTION", config.BackupConnectionString),
            EnvLine("SETUP_TOKEN", config.SetupToken)
        };

        File.WriteAllLines(envPath, lines);
        RestrictToOwner(envPath);
        Console.WriteLine($"Generated: {envPath}");
    }

    // Compose interpolates variables inside .env values, so a literal $ - entirely legal in
    // a password - would otherwise be read as the start of a reference and silently mangle
    // the value. $$ is Compose's escape for it.
    private static string EnvLine(string key, string? value)
        => $"{key}={(value ?? string.Empty).Replace("$", "$$")}";

    // The file holds the database password and setup token, so keep it owner-only.
    // No-op on Windows, where the default ACL on a user-profile path is already restrictive.
    private static void RestrictToOwner(string path)
    {
        if (OperatingSystem.IsWindows()) return;
        try
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Warning: could not restrict permissions on {path}: {ex.Message}");
        }
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "CLAUDE.md")))
            {
                return dir.FullName;
            }
            dir = dir.Parent;
        }
        return AppContext.BaseDirectory;
    }

    // Sets the execute bit directly rather than spawning chmod. The previous
    // Process.Start("chmod", ...) was never awaited, so the wizard could report the script
    // as generated - and exit - before chmod had run, intermittently leaving a script the
    // user cannot execute. No-op on Windows, which has no execute bit.
    private static void MakeExecutable(string path)
    {
        if (OperatingSystem.IsWindows()) return;
        try
        {
            File.SetUnixFileMode(path,
                UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
                UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Warning: could not make {path} executable: {ex.Message}");
            Console.WriteLine($"         Run: chmod +x \"{path}\"");
        }
    }

    // Full image reference from the registry path and tag collected in Step 3.
    private static string BuildAppImage(WizardConfig config)
    {
        var repo = string.IsNullOrWhiteSpace(config.DockerRegistry)
            ? "ghcr.io/darkgrotto/countorsell"
            : config.DockerRegistry.TrimEnd('/');
        var tag = string.IsNullOrWhiteSpace(config.DockerImageTag) ? "latest" : config.DockerImageTag;
        return $"{repo}:{tag}";
    }

    // Compose project names allow lowercase letters, digits, dashes and underscores, and
    // must start with a letter or digit. Falls back to "countorsell" when the instance name
    // has nothing usable - which is also the historical default, so the volume names stay
    // exactly as they are for a single deployment that never set one.
    private static string ProjectNameFrom(string? instanceName)
    {
        if (string.IsNullOrWhiteSpace(instanceName)) return "countorsell";

        var slug = new string(instanceName.ToLowerInvariant()
            .Select(c => char.IsLetterOrDigit(c) ? c : '-')
            .ToArray())
            .Trim('-');

        while (slug.Contains("--")) slug = slug.Replace("--", "-");

        return slug.Length > 0 && char.IsLetterOrDigit(slug[0]) ? slug : "countorsell";
    }
}
